apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    access: proxy
    url: postgres:5432
    database: tire_db
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
    isDefault: true
